version: '3'
services:
  api:
    build:
      context: ./api # Ruta al directorio de la API de Laravel
      dockerfile: Dockerfile
    ports:
      - 8000:8000
  front:
    build:
      context: ./front # Ruta al directorio del front-end de Vue.js
      dockerfile: Dockerfile
    ports:
      - 8080:8080

