version: '3'
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: mysql:5.7
    platform: linux/amd64
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ThWbgFxwqQA65D6s
      MYSQL_DATABASE: todolist
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev123456789
    volumes:
      - db_data:/var/lib/mysql
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - api
volumes:
  db_data:
